# Generated by Django 3.2.6 on 2021-08-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot_Turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Mahsulot Turi')),
            ],
            options={
                'verbose_name': 'mahsulot turi',
                'verbose_name_plural': 'mahsulot turlari',
            },
        ),
        migrations.CreateModel(
            name='Mahsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Mahsulot Nomi')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Keltirilgan Sanasi')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='korzinka_api.mahsulot_turi')),
            ],
            options={
                'verbose_name': 'mahsulot',
                'verbose_name_plural': 'mahsulotlar',
                'ordering': ['-date'],
            },
        ),
    ]
